title: Trail Buddy Demo
image: >-
  ./trailbuddy-astro-view-transition-demo.netlify.app.webp
url: 'https://trailbuddy-astro-view-transition-demo.netlify.app/'
featured: 30
highlight: true
dateAdded: 2023-11-06T21:05:41.000Z
