name: Draft minor release blog post

on: workflow_dispatch

jobs:
  draft:
    name: Draft minor release blog post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Node.js & install dependencies
        uses: ./.github/actions/setup-node-pnpm

      - name: Draft minor release blog post
        run: node scripts/draft-release-post.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
